"""Repository interfaces for Runtime Core persistence.

Runtime execution logic depends on these contracts only. Concrete
implementations start with the in-memory store; durable adapters
(PostgreSQL/Redis) must be added later behind the same interfaces.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from agent_platform.runtime.core.events import RuntimeEvent
    from agent_platform.runtime.core.models import (
        Application,
        Artifact,
        Checkpoint,
        Run,
        Session,
        State,
    )


@runtime_checkable
class RuntimeStore(Protocol):
    """Persistence contract shared by in-memory and future durable stores."""

    def save_application(self, application: Application) -> None: ...
    def get_application(self, application_id: str) -> Application | None: ...
    def list_applications(self) -> list[Application]: ...
    def save_session(self, session: Session) -> None: ...
    def get_session(self, session_id: str) -> Session | None: ...
    def list_sessions(self, application_id: str | None = None) -> list[Session]: ...
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(
        self, application_id: str | None = None, session_id: str | None = None
    ) -> list[Run]: ...
    def get_state(self, run_id: str) -> State | None: ...
    def save_state(self, state: State) -> None: ...
    def save_event(self, event: RuntimeEvent) -> None: ...
    def list_events(self, run_id: str) -> list[RuntimeEvent]: ...
    def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...
    def get_checkpoint(self, checkpoint_id: str) -> Checkpoint | None: ...
    def latest_checkpoint_for_run(self, run_id: str) -> Checkpoint | None: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
